# FILE: configs/tasks.yaml (已按新要求修改)

# ==============================================================================
# PubCrawler Task Configuration v10.1
# 修改说明:
# - 所有任务的 download_pdfs 设置为 true。
# - 所有任务的 limit 统一设置为 20。
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. DATA SOURCE DEFINITIONS ("The Encyclopedia")
# ------------------------------------------------------------------------------
source_definitions:
  arxiv:
    API: "http://export.arxiv.org/api/query?"
  openreview:
    ICLR: { venue_id: "ICLR.cc/YYYY/Conference", api_v1_years: [2019, 2020, 2021, 2022, 2023] }
    NeurIPS: { venue_id: "NeurIPS.cc/YYYY/Conference", api_v1_years: [2019, 2020, 2021, 2022] }
  html_cvf:
    CVPR: "https://openaccess.thecvf.com/CVPRYYYY?day=all"
    ICCV: "https://openaccess.thecvf.com/ICCVYYYY?day=all"
  html_pmlr:
    ICML: "https://proceedings.mlr.press/"
  html_acl:
    ACL: "https://aclanthology.org/volumes/YYYY.acl-long/"
    EMNLP: "https://aclanthology.org/volumes/YYYY.emnlp-main/"
    NAACL: { pattern_map: { 2019: "2019.naacl-main", 2021: "2021.naacl-main", 2022: "2022.naacl-main", 2024: "2024.naacl-long" } }
  selenium:
    AAAI: "https://aaai.org/aaai-publications/aaai-conference-proceedings/"
    KDD: "https://dl.acm.org/conference/kdd/proceedings"
  html_other:
    JMLR: "https://jmlr.org/papers/"

# ------------------------------------------------------------------------------
# 2. TASKS TO EXECUTE ("The Battle Plan")
# ------------------------------------------------------------------------------
tasks:
  # === ICLR: 2022 - 2026 ===
  - name: 'ICLR_2026'
    conference: 'ICLR'
    year: 2026
    source_type: 'openreview'
    enabled: true
    fetch_reviews: true
    download_pdfs: true
    limit: 20
  - name: 'ICLR_2025'
    conference: 'ICLR'
    year: 2025
    source_type: 'openreview'
    enabled: true
    fetch_reviews: true
    download_pdfs: true
    limit: 20
  - name: 'ICLR_2024'
    conference: 'ICLR'
    year: 2024
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20
  - name: 'ICLR_2023'
    conference: 'ICLR'
    year: 2023
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20
  - name: 'ICLR_2022'
    conference: 'ICLR'
    year: 2022
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20

  # === NeurIPS: 2022 - 2026 ===
  - name: 'NeurIPS_2026'
    conference: 'NeurIPS'
    year: 2026
    source_type: 'openreview'
    enabled: true
    fetch_reviews: true
    download_pdfs: true
    limit: 20
  - name: 'NeurIPS_2025'
    conference: 'NeurIPS'
    year: 2025
    source_type: 'openreview'
    enabled: true
    fetch_reviews: true
    download_pdfs: true
    limit: 20
  - name: 'NeurIPS_2024'
    conference: 'NeurIPS'
    year: 2024
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20
  - name: 'NeurIPS_2023'
    conference: 'NeurIPS'
    year: 2023
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20
  - name: 'NeurIPS_2022'
    conference: 'NeurIPS'
    year: 2022
    source_type: 'openreview'
    enabled: true
    fetch_reviews: false
    download_pdfs: true
    limit: 20

  # === ICML: 2022 - 2026 ===
  - name: 'ICML_2026'
    conference: 'ICML'
    year: 2026
    source_type: 'html_pmlr'
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ICML_2025'
    conference: 'ICML'
    year: 2025
    source_type: 'html_pmlr'
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ICML_2024'
    conference: 'ICML'
    year: 2024
    source_type: 'html_pmlr'
    url_override: "https://proceedings.mlr.press/v235/"
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ICML_2023'
    conference: 'ICML'
    year: 2023
    source_type: 'html_pmlr'
    url_override: "https://proceedings.mlr.press/v202/"
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ICML_2022'
    conference: 'ICML'
    year: 2022
    source_type: 'html_pmlr'
    url_override: "https://proceedings.mlr.press/v162/"
    enabled: true
    download_pdfs: true
    limit: 20

  # === ACL: 2022 - 2026 ===
  - name: 'ACL_2026'
    conference: 'ACL'
    year: 2026
    source_type: 'html_acl'
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ACL_2025'
    conference: 'ACL'
    year: 2025
    source_type: 'html_acl'
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ACL_2024'
    conference: 'ACL'
    year: 2024
    source_type: 'html_acl'
    url_override: "https://aclanthology.org/volumes/2024.acl-long/"
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ACL_2023'
    conference: 'ACL'
    year: 2023
    source_type: 'html_acl'
    enabled: true
    download_pdfs: true
    limit: 20
  - name: 'ACL_2022'
    conference: 'ACL'
    year: 2022
    source_type: 'html_acl'
    enabled: true
    download_pdfs: true
    limit: 20